# Use Python base image
FROM python:3.11-slim

# Install gfortran
RUN apt-get update && \
    apt-get install -y gfortran && \
    apt-get clean

# Set the working directory
WORKDIR /app

# Copy all files to /app
COPY . .

# Install Python dependencies
RUN pip install flask flask-cors

# Expose port 5000 for Flask
EXPOSE 5000

# Run the Flask app
CMD ["python", "app.py"]
