# Base image with gfortran installed
FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && \
    apt-get install -y python3 python3-pip gfortran && \
    apt-get clean

# Create app directory
WORKDIR /app

# Copy your app files
COPY . /app

# Install Python dependencies
RUN pip3 install -r requirements.txt

# Expose the port
EXPOSE 5000

# Run the Flask app
CMD ["python3", "app.py"]
